### ISSUE TITLE
Travis CIを導入する

### ISSUE THREAD

**Issue by ry023** [ry023/railstutorial#14]
Travisくんを召喚する

**Comment by Asuforce** [comment]
やってくぞ！

**Comment by ry023** [comment]
`Gemfile`に
```
group :development, :test do
  gem 'sqlite3',     '1.3.9'
  ...(中略)
end
```
って書いてて、travisで
```
bundle install --without development --deployment
```
を実行したが、何故かsqlite3がインストールされているっぽい？
```
Installing sqlite3 1.3.9 with native extensions
```
https://s3.amazonaws.com/archive.travis-ci.org/jobs/139949854/log.txt

ふしぎだ

**Comment by shimoju** [comment]
@ry023 
`group :development, :test`は両方のグループに属しているってことなんで、
developmentのインストールを省略してもtestの方でインストールされちゃう

**Comment by ry023** [comment]
なるほどね！！！　解決したありがとう
