### ISSUE TITLE
webhookでSlackと連携

### ISSUE THREAD

**Issue by ry023** [ry023/railstutorial#5]
Slackで通知いくようにしましょう

**Comment by tnmt** [comment]
https://pepabo.slack.com/apps/manage/A0F7YS2SX-github が既にあるんで、使ったら良いよ〜

**Comment by ry023** [comment]
おお！　こっち使う感じで設定し直してみます！
ありがとうございます

**Comment by ry023** [comment]
done!
このコメントが通知されてれば成功
